CREATE TABLE talk
(
    id             UUID NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    book_id        UUID,
    member_id      UUID,
    content        VARCHAR(255),
    time_to_hidden TIMESTAMP WITHOUT TIME ZONE,
    like_count     BIGINT,
    support_count  BIGINT,
    CONSTRAINT pk_talk PRIMARY KEY (id)
);

CREATE INDEX idx_talk_book_id ON talk (book_id);

CREATE INDEX idx_talk_created_at ON talk (created_at);

CREATE INDEX idx_talk_member_id ON talk (member_id);

--

CREATE TABLE reaction
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    talk_id    UUID,
    member_id  UUID,
    type       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_reaction PRIMARY KEY (id)
);

ALTER TABLE reaction
    ADD CONSTRAINT uq_reaction_talk_member_type UNIQUE (talk_id, member_id, type);

CREATE INDEX idx_reaction_member_id ON reaction (member_id);

CREATE INDEX idx_reaction_talk_id ON reaction (talk_id);

CREATE INDEX idx_reaction_type ON reaction (type);

--

CREATE TABLE book
(
    id                  UUID NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    title               VARCHAR(255),
    isbn                VARCHAR(255),
    author              VARCHAR(255),
    thumbnail_image_url TEXT,
    description         TEXT,
    external_link_url   TEXT,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE INDEX idx_book_isbn ON book (isbn);

CREATE INDEX idx_book_title ON book (title);

--

CREATE TABLE customer_message
(
    id         UUID NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    message    TEXT,
    CONSTRAINT pk_customer_message PRIMARY KEY (id)
);


--

CREATE TABLE member
(
    id             UUID NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    role           VARCHAR(255),
    status         VARCHAR(255),
    login_id       VARCHAR(255),
    login_password TEXT,
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE INDEX idx_member_login_id ON member (login_id);
